/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author markh_000
 */
public class MainFrame extends javax.swing.JFrame {

    private ArrayList<Auction> auctionsListe;
    private ArrayList<AuctionPanel> apListe;
    private User buyer;
    private int i;
    private Auction at;
    private Search search;
    private String maxPrise;
    private int maxPris;

    /**
     * Creates new form main
     */
    public MainFrame(ArrayList<Auction> auctionsListe, User buyer) {

        initComponents();
        this.auctionsListe = auctionsListe;
        apListe = new ArrayList<>();
        this.buyer = buyer;
        this.setTitle(buyer.getName());
        createPanels(auctionsListe);
        setJcombobox();
    }

    private void createPanels(ArrayList<Auction> auctionsLis) {

        int x = 0;
        int y = 0;
        int height = 0;
        for (Auction auction : auctionsLis) {

            AuctionPanel ap = new AuctionPanel(auction, this);
            ap.setLocation(x, y);
            jPanel_SamletAktion.add(ap);
            y += ap.getHeight();
            ap.setVisible(true);
            height = ap.getHeight();
        }
        if (auctionsLis.size() > 4) {
            int width = jPanel_SamletAktion.getWidth();
            height *= auctionsListe.size();
            jPanel_SamletAktion.setPreferredSize(new Dimension(width, height));
            width += 18;
            jScrollPane1.setPreferredSize(new Dimension(width, height));
        }
    }

    public User getBuyer() {
        return buyer;
    }

    private void setJcombobox() {
        jComboBox1.removeAllItems();
        Search search = new Search(auctionsListe);
        for (Object s : search.getProdukt()) {
            jComboBox1.addItem(s);
        }

    }

    public ArrayList<Auction> getSpecificAuction(String product) throws Exception {
        ArrayList<Auction> al = new ArrayList<>();
        try {
            {
                maxPris = Integer.parseInt(maxPrise);
                
            }
        } catch (Exception e) {
            throw new Exception("Tegn og Bokstaver kan bruges.");
        }
            
        for (Auction auction : auctionsListe) {
            switch (product) {
                case "Furniture":
                    if (auction.getProduct() instanceof Furniture) {
                        if (auction.getLatestBid() <= maxPris) {
                            al.add(auction);
                        } else {
                            throw new Exception("Beløbet er for småt");
                        }
                    }
                    break;
                case "Jewellery":
                    if (auction.getProduct() instanceof Jewellery) {
                        if (auction.getLatestBid() <= maxPris) {
                            al.add(auction);
                        } else {
                            throw new Exception("Beløbet er for småt");
                        }
                    }
                    break;
                case "Painting":
                    if (auction.getProduct() instanceof Painting) {
                        if (auction.getLatestBid() <= maxPris) {
                            al.add(auction);
                        } else {
                            throw new Exception("Beløbet er for småt");
                        }
                    }
                    break;
                case "Wine":
                    if (auction.getProduct() instanceof Wine) {
                        if (auction.getLatestBid() <= maxPris) {
                            al.add(auction);
                        } else {
                            throw new Exception("Beløbet er for småt");
                        }
                    }
                    break;
                default:
                    al = auctionsListe;
                    break;
            }

        }
        jPanel_SamletAktion.removeAll();
        createPanels(al);
        jPanel_SamletAktion.updateUI();
        return al;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel_SamletAktion = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_pris = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Næstved Aktionshus");

        javax.swing.GroupLayout jPanel_SamletAktionLayout = new javax.swing.GroupLayout(jPanel_SamletAktion);
        jPanel_SamletAktion.setLayout(jPanel_SamletAktionLayout);
        jPanel_SamletAktionLayout.setHorizontalGroup(
            jPanel_SamletAktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        jPanel_SamletAktionLayout.setVerticalGroup(
            jPanel_SamletAktionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel_SamletAktion);

        jButton1.setText("Søg");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Type:" }));

        jButton2.setText("Tilbage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Max Pris:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField_pris))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_pris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        maxPrise = jTextField_pris.getText();
        if ("".equals(maxPrise) || "0".equals(maxPrise)) {
                maxPrise = "10000000";
                System.out.println("hej");
            }

        String selectedItem = (String) jComboBox1.getSelectedItem();
        try {
            getSpecificAuction(selectedItem);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            getSpecificAuction("hej");
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_SamletAktion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_pris;
    // End of variables declaration//GEN-END:variables
}
