/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.*;
import utility.CardHandler;

/**
 *
 * @author markh_000
 */
public class MainFrame1 extends javax.swing.JFrame {

    
private CardLayout cl;
    private CardHandler ch;
    private ArrayList<Auction> auctionsList;
    private User buyer;
    private AuctionSiden as;
    private CreateProduct cp;
    private CreateUser cu;
    
    public static final String HOVEDPANEL = "hp";
    public static final String AUCTIONSIDE = "as";
    public static final String CREATEPRODUCT = "cp";
    public static final String CREATEUSER = "cu";
    
    /**
     * Creates new form main
     */
    public MainFrame1(ArrayList<Auction> auctionsList, User buyer) {
        this.auctionsList = auctionsList;
        this.buyer = buyer;
        initComponents();
        setTitle(buyer.getName());
        setSize(new Dimension(750, 600));
        ch = new CardHandler(cl, jPanel1,this);
        addPages();
        
    }
    public void addPages(){
        HovdePanel hp = new HovdePanel(auctionsList, buyer, this);
        ch.addPage(hp, HOVEDPANEL);
        
        as = new AuctionSiden(buyer, this);
        ch.addPage(as, AUCTIONSIDE);
        ch.show(HOVEDPANEL);
        
        cp = new CreateProduct(auctionsList, buyer, this);
        ch.addPage(cp, CREATEPRODUCT);
        
        cu = new CreateUser();
        ch.addPage(cu, CREATEUSER);
        
    }
    public CardHandler getCardHandler(){
        return ch;
    }
    public AuctionSiden getAuctionSiden(){
        return as;
    }
    
    public void createProduct(Auction auction){
        
        auctionsList.add(auction);
        
        
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
