/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package veiw.Panel;
import java.awt.Dimension;
import model.*;
//import model.handler.*;

/**
 *
 * @author MarcoPc
 */
public class TicketGroupPanel extends javax.swing.JPanel {
//private Listeners listeners;
//private TicketHandler ticketHandler;
//private TicketType ticketType;
//private KurvHandler kurvHandler;
    /**
     * Creates new form NewJPanel
     */
//    public TicketGroupPanel(Listeners listeners1, TicketHandler ticketHandler1, TicketType ticketType1, KurvHandler kurvHandler) {
//        this.listeners = listeners1;
//        this.ticketHandler = ticketHandler1;
//        this.ticketType = ticketType1;
//        this.kurvHandler = kurvHandler;
//        int x = 0;
//        x = 323;
//        setSize(new Dimension(x, 40));
//        initComponents();
//        jButton.setText(ticketType.getType());
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
////     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton = new javax.swing.JButton();

        jButton.setText("jButton1");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
//        ticketHandler.setSpecTicket(ticketType);
//        kurvHandler.setTypeView("Ticket");
    }//GEN-LAST:event_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    // End of variables declaration//GEN-END:variables
}
